resources:
- repo: self
  clean: true

trigger:
- master

name: Ideine.Cache-CI-$(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)

pool:
  vmImage: 'windows-latest'

steps:
- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: 'Ideine.Cache.sln'

- task: MSBuild@1
  displayName: 'Build solution **/*.sln'
  inputs:
    configuration: Release
    msbuildArguments: '/t:Restore;Build;Pack /p:PackageOutputPath="artifacts/"'

- task: CopyFiles@2
  displayName: "Copy Files to: $(build.artifactstagingdirectory)"
  inputs:
    SourceFolder: artifacts
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: and(succeeded(), in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/develop')) 

- task: PublishBuildArtifacts@1
  displayName: "Publish Artifact: drop"
  condition: and(succeeded(), in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/develop')) 
