resources:
- repo: self
  clean: true

trigger:
- master

name: Xmf2.Cache-CI-$(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: 'Xmf2.Cache.sln'

- task: DotNetCoreCli@2
  displayName: "Build solution"
  inputs:
    command: 'pack'
    packagesToPack: 'Xmf2.Cache.sln'
    configuration: 'Release'
    versioningScheme: 'off'
  condition: succeeded()

- task: PublishBuildArtifacts@1
  displayName: "Publish Artifact: drop"
  condition: succeeded()
